version: '3.8'

services:
  # ----------------------------------------
  # 1. PREFECT SERVER
  # Berfungsi sebagai pengatur jadwal otomatis (Orkestrasi)
  # ----------------------------------------
  prefect:
    build: .                       # <-- Tetap mengarah ke Dockerfile lokal
    container_name: eco_prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"                # Port default untuk UI Prefect
    volumes:
      - ./flows:/opt/prefect/flows # Folder flows milikmu
      - ./data:/opt/prefect/data   # Folder penyimpanan DuckDB & CSV
    environment:
      - PREFECT_API_URL=http://127.0.0.1:4200/api

  # ----------------------------------------
  # 2. METABASE COMMUNITY EDITION
  # Berfungsi untuk visualisasi dashboard interaktif
  # ----------------------------------------
  metabase:
    image: metabase/metabase:latest
    container_name: eco_metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
      - ./data:/data
      - ./metabase-plugins:/plugins
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db