version: '3.8'

services:
  # ----------------------------------------
  # 1. APACHE AIRFLOW
  # Berfungsi sebagai pengatur jadwal otomatis (Orkestrasi)
  # ----------------------------------------
  airflow:
    image: apache/airflow:2.8.1
    container_name: eco_airflow
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false

  # ----------------------------------------
  # 2. METABASE COMMUNITY EDITION
  # Berfungsi untuk visualisasi dashboard interaktif
  # ----------------------------------------
  metabase:
    image: metabase/metabase:latest
    container_name: eco_metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
      - ./data:/data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db